# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_x64)
  hsrans_config = release_x64

else ifeq ($(config),debug_x64)
  hsrans_config = debug_x64

else ifeq ($(config),releaseclang_x64)
  hsrans_config = releaseclang_x64

else ifeq ($(config),debugclang_x64)
  hsrans_config = debugclang_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := hsrans

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

hsrans:
ifneq (,$(hsrans_config))
	@echo "==== Building hsrans ($(hsrans_config)) ===="
	@${MAKE} --no-print-directory -C . -f hsrans.make config=$(hsrans_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f hsrans.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_x64"
	@echo "  debug_x64"
	@echo "  releaseclang_x64"
	@echo "  debugclang_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   hsrans"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"